/*
 * Fresnel Editor
 */

package cz.muni.fi.fresneleditor.common.reposconf;

import java.util.ArrayList;

import cz.muni.fi.fresneleditor.common.utils.GuiUtils;
import cz.muni.fi.fresneleditor.model.BaseRepositoryDao;

/**
 * This class provides main configuration dialog for Fresnel Editor.
 * 
 * @author Miroslav Warchil (warmir@mail.muni.cz)
 */
public class FresnelEditorConfigurationDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form RepositoriesConfigurationJDialog.
	 */
	public FresnelEditorConfigurationDialog(java.awt.Component parent) {
		super(GuiUtils.getOwnerFrame(parent), true);
		initComponents();
		GuiUtils.centerOnScreen(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		configurationTabbedPane = new javax.swing.JTabbedPane();
		repositoriesConfigurationJPanel = new cz.muni.fi.fresneleditor.common.reposconf.RepositoriesConfigurationJPanel(
				true);
		namespacesConfigurationJPanel = new cz.muni.fi.fresneleditor.common.reposconf.NamespacesConfigurationJPanel(
				new ArrayList<BaseRepositoryDao>());
		closeBtn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(
						cz.muni.fi.fresneleditor.common.FresnelApplication.class)
				.getContext()
				.getResourceMap(FresnelEditorConfigurationDialog.class);
		setTitle(resourceMap.getString("Form.title")); // NOI18N
		setName("Form"); // NOI18N

		configurationTabbedPane.setName("configurationTabbedPane"); // NOI18N

		repositoriesConfigurationJPanel
				.setName("repositoriesConfigurationJPanel"); // NOI18N
		configurationTabbedPane
				.addTab(resourceMap
						.getString("repositoriesConfigurationJPanel.TabConstraints.tabTitle"),
						repositoriesConfigurationJPanel); // NOI18N

		namespacesConfigurationJPanel.setName("namespacesConfigurationJPanel"); // NOI18N
		configurationTabbedPane
				.addTab(resourceMap
						.getString("namespacesConfigurationJPanel.TabConstraints.tabTitle"),
						namespacesConfigurationJPanel); // NOI18N

		closeBtn.setText(resourceMap.getString("closeBtn.text")); // NOI18N
		closeBtn.setName("closeBtn"); // NOI18N
		closeBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(closeBtn,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										78,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(10, 10, 10))
				.addComponent(configurationTabbedPane,
						javax.swing.GroupLayout.DEFAULT_SIZE, 646,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(configurationTabbedPane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(closeBtn)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeBtnActionPerformed
		this.dispose();
	}// GEN-LAST:event_closeBtnActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton closeBtn;
	private javax.swing.JTabbedPane configurationTabbedPane;
	private cz.muni.fi.fresneleditor.common.reposconf.NamespacesConfigurationJPanel namespacesConfigurationJPanel;
	private cz.muni.fi.fresneleditor.common.reposconf.RepositoriesConfigurationJPanel repositoriesConfigurationJPanel;
	// End of variables declaration//GEN-END:variables

}
