/*
 * Fresnel Editor
 */

package cz.muni.fi.fresneleditor.common.reposconf;

import org.openrdf.rio.RDFFormat;
import org.springframework.util.Assert;

/**
 * 
 * @author Igor Zemsky (zemsky@mail.muni.cz)
 */
public class RdfDataFormatJPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form RdfDataFormatJPanel
	 */
	public RdfDataFormatJPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		n3Radio = new javax.swing.JRadioButton();
		rdfxmlRadio = new javax.swing.JRadioButton();
		ntriplesRadio = new javax.swing.JRadioButton();
		turtleRadio = new javax.swing.JRadioButton();

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(
						cz.muni.fi.fresneleditor.common.FresnelApplication.class)
				.getContext().getResourceMap(RdfDataFormatJPanel.class);
		setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap
				.getString("Form.border.title"))); // NOI18N
		setName("Form"); // NOI18N

		buttonGroup1.add(n3Radio);
		n3Radio.setFont(resourceMap.getFont("n3Radio.font")); // NOI18N
		n3Radio.setSelected(true);
		n3Radio.setText(resourceMap.getString("n3Radio.text")); // NOI18N
		n3Radio.setName("n3Radio"); // NOI18N

		buttonGroup1.add(rdfxmlRadio);
		rdfxmlRadio.setFont(resourceMap.getFont("n3Radio.font")); // NOI18N
		rdfxmlRadio.setText(resourceMap.getString("rdfxmlRadio.text")); // NOI18N
		rdfxmlRadio.setName("rdfxmlRadio"); // NOI18N

		buttonGroup1.add(ntriplesRadio);
		ntriplesRadio.setFont(resourceMap.getFont("n3Radio.font")); // NOI18N
		ntriplesRadio.setText(resourceMap.getString("ntriplesRadio.text")); // NOI18N
		ntriplesRadio.setName("ntriplesRadio"); // NOI18N

		buttonGroup1.add(turtleRadio);
		turtleRadio.setFont(resourceMap.getFont("n3Radio.font")); // NOI18N
		turtleRadio.setText(resourceMap.getString("turtleRadio.text")); // NOI18N
		turtleRadio.setName("turtleRadio"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		n3Radio))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		rdfxmlRadio))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		ntriplesRadio))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		turtleRadio)))
								.addContainerGap(316, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(n3Radio)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(rdfxmlRadio)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(ntriplesRadio)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										1, Short.MAX_VALUE)
								.addComponent(turtleRadio).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JRadioButton n3Radio;
	private javax.swing.JRadioButton ntriplesRadio;
	private javax.swing.JRadioButton rdfxmlRadio;
	private javax.swing.JRadioButton turtleRadio;

	// End of variables declaration//GEN-END:variables

	public RDFFormat getSelectedFormat() {
		RDFFormat rdfFormat = null;
		if (n3Radio.isSelected()) {
			rdfFormat = RDFFormat.N3;
		} else if (ntriplesRadio.isSelected()) {
			rdfFormat = RDFFormat.NTRIPLES;
		} else if (turtleRadio.isSelected()) {
			rdfFormat = RDFFormat.TURTLE;
		} else if (rdfxmlRadio.isSelected()) {
			rdfFormat = RDFFormat.RDFXML;
		} else {
			Assert.isTrue(false, "We should never get here");
		}
		return rdfFormat;
	}
}
