/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerEditJPanel.java
 *
 * Created on May 9, 2012, 2:30:42 PM
 */
package cz.muni.fi.fresneleditor.gui.mod.portal;

/**
 *
 * @author nodrock
 */
public class ServerEditJPanel extends javax.swing.JPanel {

    /** Creates new form ServerEditJPanel */
    public ServerEditJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverListJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serverList = new javax.swing.JList();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        editServerJPanel = new javax.swing.JPanel();
        serverUrlTextField = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/fresneleditor/gui/mod/portal/FresnelPortalBundle"); // NOI18N
        serverListJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("serverListJPanelTitle"))); // NOI18N
        serverListJPanel.setName("serverListJPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        serverList.setName("serverList"); // NOI18N
        jScrollPane1.setViewportView(serverList);

        btnDelete.setText(bundle.getString("delete")); // NOI18N
        btnDelete.setName("btnDelete"); // NOI18N

        btnEdit.setText(bundle.getString("bedit")); // NOI18N
        btnEdit.setName("btnEdit"); // NOI18N

        btnCreate.setText(bundle.getString("create")); // NOI18N
        btnCreate.setName("btnCreate"); // NOI18N

        org.jdesktop.layout.GroupLayout serverListJPanelLayout = new org.jdesktop.layout.GroupLayout(serverListJPanel);
        serverListJPanel.setLayout(serverListJPanelLayout);
        serverListJPanelLayout.setHorizontalGroup(
            serverListJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, serverListJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(serverListJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .add(serverListJPanelLayout.createSequentialGroup()
                        .add(btnCreate)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnEdit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnDelete)))
                .addContainerGap())
        );
        serverListJPanelLayout.setVerticalGroup(
            serverListJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serverListJPanelLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverListJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnDelete)
                    .add(btnEdit)
                    .add(btnCreate))
                .addContainerGap(3, Short.MAX_VALUE))
        );

        editServerJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("editServerJPanelTitle"))); // NOI18N
        editServerJPanel.setName("editServerJPanel"); // NOI18N

        serverUrlTextField.setName("serverUrlTextField"); // NOI18N

        urlLabel.setText(bundle.getString("urlLabel")); // NOI18N
        urlLabel.setName("urlLabel"); // NOI18N

        btnSave.setText(bundle.getString("save")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N

        org.jdesktop.layout.GroupLayout editServerJPanelLayout = new org.jdesktop.layout.GroupLayout(editServerJPanel);
        editServerJPanel.setLayout(editServerJPanelLayout);
        editServerJPanelLayout.setHorizontalGroup(
            editServerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editServerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(urlLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverUrlTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSave)
                .addContainerGap())
        );
        editServerJPanelLayout.setVerticalGroup(
            editServerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editServerJPanelLayout.createSequentialGroup()
                .add(editServerJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(urlLabel)
                    .add(serverUrlTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnSave))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serverListJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(editServerJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(serverListJPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 286, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(editServerJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel editServerJPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList serverList;
    private javax.swing.JPanel serverListJPanel;
    private javax.swing.JTextField serverUrlTextField;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables
}
