/*
 * Fresnel Editor
 */

package cz.muni.fi.fresneleditor.common.guisupport.dialogs;

/**
 * Dialog for showing and editing details about Fresnel elements.
 * 
 * @author Miroslav Warchil (warmir@mail.muni.cz)
 * @date 1.1.2010
 */
public class ElementDetailDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String description;

	/**
	 * Creates new form ElementDetailDialog
	 */
	public ElementDetailDialog(java.awt.Frame parent, boolean modal,
			String description) {
		super(parent, modal);
		initComponents();
		this.description = description;
		loadDescription();
	}

	private void loadDescription() {
		if (description == null || "".equals(description)) {
			textArea.setText("");
		} else {
			textArea.setText(description);
		}
	}

	public String getDescription() {
		return this.description;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		descriptionLbl = new javax.swing.JLabel();
		textScrollPane = new javax.swing.JScrollPane();
		textArea = new javax.swing.JTextArea();
		saveBtn = new javax.swing.JToggleButton();
		cancelBtn = new javax.swing.JToggleButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(
						cz.muni.fi.fresneleditor.common.FresnelApplication.class)
				.getContext().getResourceMap(ElementDetailDialog.class);
		setTitle(resourceMap.getString("Form.title")); // NOI18N
		setName("Form"); // NOI18N

		descriptionLbl.setText(resourceMap.getString("descriptionLbl.text")); // NOI18N
		descriptionLbl.setName("descriptionLbl"); // NOI18N

		textScrollPane.setName("textScrollPane"); // NOI18N

		textArea.setColumns(20);
		textArea.setFont(resourceMap.getFont("textArea.font")); // NOI18N
		textArea.setLineWrap(true);
		textArea.setRows(5);
		textArea.setName("textArea"); // NOI18N
		textScrollPane.setViewportView(textArea);

		saveBtn.setText(resourceMap.getString("saveBtn.text")); // NOI18N
		saveBtn.setName("saveBtn"); // NOI18N
		saveBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveBtnActionPerformed(evt);
			}
		});

		cancelBtn.setText(resourceMap.getString("cancelBtn.text")); // NOI18N
		cancelBtn.setName("cancelBtn"); // NOI18N
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(193, Short.MAX_VALUE)
								.addComponent(cancelBtn,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										89,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(saveBtn,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										89,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														textScrollPane,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														367,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(descriptionLbl))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(descriptionLbl)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(textScrollPane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										126,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(saveBtn)
												.addComponent(cancelBtn))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBtnActionPerformed
		this.dispose();
	}// GEN-LAST:event_cancelBtnActionPerformed

	private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveBtnActionPerformed
		this.description = textArea.getText();
		this.dispose();
	}// GEN-LAST:event_saveBtnActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JToggleButton cancelBtn;
	private javax.swing.JLabel descriptionLbl;
	private javax.swing.JToggleButton saveBtn;
	private javax.swing.JTextArea textArea;
	private javax.swing.JScrollPane textScrollPane;
	// End of variables declaration//GEN-END:variables

}
