/*
 * Fresnel Editor
 */

package cz.muni.fi.fresneleditor.gui.mod.format.dialogs;

import java.util.ResourceBundle;

import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import cz.muni.fi.fresneleditor.common.ContextHolder;
import cz.muni.fi.fresneleditor.common.data.DomainType;
import cz.muni.fi.fresneleditor.common.data.SelectorType;
import cz.muni.fi.fresneleditor.common.guisupport.MessageDialog;
import cz.muni.fi.fresneleditor.common.utils.FresnelUtils;
import cz.muni.fi.fresneleditor.common.utils.GuiUtils;
import cz.muni.fi.fresneleditor.gui.mod.format.data.DomainSelectorGuiWrapper;

/**
 * Dialog allowing editing of domain selector.
 * 
 * @author Miroslav Warchil
 * @version 21.3.2009
 */
public class DomainSelectorDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static final Logger LOG = LoggerFactory
			.getLogger(DomainSelectorDialog.class);
	private static final ResourceBundle bundle = java.util.ResourceBundle
			.getBundle("cz/muni/fi/fresneleditor/gui/mod/format/resource-bundle-format");

	private DomainSelectorGuiWrapper domainSelector = null;

	/**
	 * Creates new form DomainSelectorDialog.
	 */
	public DomainSelectorDialog(java.awt.Frame parent, boolean modal,
			DomainSelectorGuiWrapper domainSelector) {
		super(parent, modal);
		initComponents();
		// Load domain selector into dialog components
		this.domainSelector = domainSelector;
		loadDomainSelector();
	}

	/**
	 * Fills dialog components with information about given domain selector.
	 */
	private void loadDomainSelector() {

		JRadioButton selectedDomainTypeRadio = null;

		switch (domainSelector.getDomainType()) {
		case CLASS:
			selectedDomainTypeRadio = classDomainRadio;
			break;
		case INSTANCE:
			selectedDomainTypeRadio = instanceDomainRadio;
			break;
		case PROPERTY:
			selectedDomainTypeRadio = propertyDomainRadio;
			break;
		default:
			LOG.error("Invalid domain type of given domain selector!");
			throw new IndexOutOfBoundsException("domainType");
		}

		JRadioButton selectedSelectorTypeRadio = null;

		switch (domainSelector.getSelectorType()) {
		case SIMPLE:
			selectedSelectorTypeRadio = simpleSelectorRadio;
			break;
		case FSL:
			selectedSelectorTypeRadio = fslQueryRadio;
			break;
		case SPARQL:
			selectedSelectorTypeRadio = sparqlQueryRadio;
			break;
		default:
			LOG.error("Invalid selector type of given domain selector!");
			throw new IndexOutOfBoundsException("selectorType");
		}

		// New final variables are needed for access in invokeLater() method.
		final JRadioButton selectedDomainTypeRadioFinal = selectedDomainTypeRadio;
		final JRadioButton selectedSelectorTypeRadioFinal = selectedSelectorTypeRadio;

		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				selectedDomainTypeRadioFinal.setSelected(true);
				selectedSelectorTypeRadioFinal.setSelected(true);
				selectorStringText.setText(domainSelector.getSelectorString());
			}
		});
	}

	/**
	 * TODO: Maybe empty
	 */
	private void saveDomainSelector() {

		if (propertyDomainRadio.isSelected()) {
			domainSelector.setDomainType(DomainType.PROPERTY);
		} else if (instanceDomainRadio.isSelected()) {
			domainSelector.setDomainType(DomainType.INSTANCE);
		} else if (classDomainRadio.isSelected()) {
			domainSelector.setDomainType(DomainType.CLASS);
		} else {
			LOG.warn("None of domain type radio buttons is selected!");
		}

		if (simpleSelectorRadio.isSelected()) {
			domainSelector.setSelectorType(SelectorType.SIMPLE);
		} else if (fslQueryRadio.isSelected()) {
			domainSelector.setSelectorType(SelectorType.FSL);
		} else if (sparqlQueryRadio.isSelected()) {
			domainSelector.setSelectorType(SelectorType.SPARQL);
		} else {
			LOG.warn("None of selector type radio buttons is selected!");
		}

		if (SelectorType.SIMPLE.equals(domainSelector.getSelectorType())
				&& (DomainType.CLASS.equals(domainSelector.getDomainType()) || (DomainType.PROPERTY
						.equals(domainSelector.getDomainType())))) {
			domainSelector.setSelectorString(FresnelUtils
					.replacePrefix(selectorStringText.getText()));
		} else {
			domainSelector.setSelectorString(selectorStringText.getText());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		domainTypeBtnGroup = new javax.swing.ButtonGroup();
		selectorTypeBtnGroup = new javax.swing.ButtonGroup();
		propertyDomainRadio = new javax.swing.JRadioButton();
		instanceDomainRadio = new javax.swing.JRadioButton();
		classDomainRadio = new javax.swing.JRadioButton();
		domainTypeLabel = new javax.swing.JLabel();
		selectorTypeLabel = new javax.swing.JLabel();
		fslQueryRadio = new javax.swing.JRadioButton();
		sparqlQueryRadio = new javax.swing.JRadioButton();
		simpleSelectorRadio = new javax.swing.JRadioButton();
		selectorStringLabel = new javax.swing.JLabel();
		saveBtn = new javax.swing.JButton();
		cancelBtn = new javax.swing.JButton();
		selectorStringScrollPane = new javax.swing.JScrollPane();
		selectorStringText = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(bundle.getString("Format_domain_editor"));
		setModal(true);

		domainTypeBtnGroup.add(propertyDomainRadio);
		propertyDomainRadio.setSelected(true);
		propertyDomainRadio.setText(bundle.getString("property_domain"));
		propertyDomainRadio.setName("propertyDomainRadio"); // NOI18N

		domainTypeBtnGroup.add(instanceDomainRadio);
		instanceDomainRadio.setText(bundle.getString("instance_domain"));
		instanceDomainRadio.setName("instanceDomainRadio"); // NOI18N

		domainTypeBtnGroup.add(classDomainRadio);
		classDomainRadio.setText(bundle.getString("class_domain"));
		classDomainRadio.setName("classDomainRadio"); // NOI18N

		domainTypeLabel.setText(bundle.getString("Selector_domain") + ":");
		domainTypeLabel.setName("domainTypeLabel"); // NOI18N

		selectorTypeLabel.setText(bundle.getString("Selector_type") + ":");
		selectorTypeLabel.setName("selectorTypeLabel"); // NOI18N

		selectorTypeBtnGroup.add(fslQueryRadio);
		fslQueryRadio.setText(bundle.getString("FSL_query"));
		fslQueryRadio.setName("fslQueryRadio"); // NOI18N

		selectorTypeBtnGroup.add(sparqlQueryRadio);
		sparqlQueryRadio.setText(bundle.getString("SPARQL_query"));
		sparqlQueryRadio.setName("sparqlQueryRadio"); // NOI18N

		selectorTypeBtnGroup.add(simpleSelectorRadio);
		simpleSelectorRadio.setSelected(true);
		simpleSelectorRadio.setText(bundle.getString("Simple_selector"));
		simpleSelectorRadio.setName("simpleSelectorRadio"); // NOI18N

		selectorStringLabel.setText(bundle.getString("Selector_string") + ":");
		selectorStringLabel.setName("selectorStringLabel"); // NOI18N

		saveBtn.setText(bundle.getString("Save"));
		saveBtn.setName("saveBtn"); // NOI18N
		saveBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveBtnActionPerformed(evt);
			}
		});

		cancelBtn.setText(bundle.getString("Cancel"));
		cancelBtn.setName("cancelBtn"); // NOI18N
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});

		selectorStringScrollPane.setName("selectorStringScrollPane"); // NOI18N

		selectorStringText.setColumns(20);
		selectorStringText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
		selectorStringText.setRows(5);
		selectorStringText.setName("selectorStringText"); // NOI18N
		selectorStringScrollPane.setViewportView(selectorStringText);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addContainerGap()
																																								.addComponent(
																																										domainTypeLabel))
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGap(22,
																																										22,
																																										22)
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														instanceDomainRadio)
																																												.addComponent(
																																														propertyDomainRadio)
																																												.addComponent(
																																														classDomainRadio))))
																																.addGap(43,
																																		43,
																																		43)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						selectorTypeLabel)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGap(10,
																																										10,
																																										10)
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														fslQueryRadio)
																																												.addComponent(
																																														sparqlQueryRadio)
																																												.addComponent(
																																														simpleSelectorRadio)))))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addContainerGap()
																																.addComponent(
																																		selectorStringLabel)))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										10,
																										Short.MAX_VALUE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addContainerGap()
																								.addComponent(
																										cancelBtn)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																.addComponent(
																		saveBtn,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		69,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		selectorStringScrollPane,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		346,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(17, 17, 17)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(domainTypeLabel)
												.addComponent(selectorTypeLabel))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														propertyDomainRadio)
												.addComponent(
														simpleSelectorRadio))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														instanceDomainRadio)
												.addComponent(fslQueryRadio))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(classDomainRadio)
												.addComponent(sparqlQueryRadio))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(selectorStringLabel)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(selectorStringScrollPane,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										142, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(saveBtn)
												.addComponent(cancelBtn))
								.addContainerGap()));

		pack();
	}// </editor-fold>                        

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBtnActionPerformed
		domainSelector.setUpdated(false);
		this.dispose();
	}// GEN-LAST:event_cancelBtnActionPerformed

	private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveBtnActionPerformed
		if (validateForm()) {
			this.saveDomainSelector();
			domainSelector.setUpdated(true);
			this.dispose();
		}
	}// GEN-LAST:event_saveBtnActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelBtn;
	private javax.swing.JRadioButton classDomainRadio;
	private javax.swing.ButtonGroup domainTypeBtnGroup;
	private javax.swing.JLabel domainTypeLabel;
	private javax.swing.JRadioButton fslQueryRadio;
	private javax.swing.JRadioButton instanceDomainRadio;
	private javax.swing.JRadioButton propertyDomainRadio;
	private javax.swing.JButton saveBtn;
	private javax.swing.JLabel selectorStringLabel;
	private javax.swing.JScrollPane selectorStringScrollPane;
	private javax.swing.JTextArea selectorStringText;
	private javax.swing.ButtonGroup selectorTypeBtnGroup;
	private javax.swing.JLabel selectorTypeLabel;
	private javax.swing.JRadioButton simpleSelectorRadio;
	private javax.swing.JRadioButton sparqlQueryRadio;

	// End of variables declaration//GEN-END:variables

	private boolean validateForm() {

		// 1. For PROPERTY-BASIC: String->URI (target must be property URI ->
		// validation to URI is
		// sufficient)
		// 2. For PROPERTY-FSL: String->valid FSL path (target is probably
		// undetectable)
		// 3. For PROPERTY-SPARQL: String->valid SPARQL query (target is
		// probably unreachable)

		String selectorString = selectorStringText.getText().trim();

		if (simpleSelectorRadio.isSelected()) {
			String validateMessage = null; 
//                        FresnelUtils.validateResourceUri(
//					selectorString, ContextHolder.getInstance()
//							.getFresnelRepositoryDao());
			if (validateMessage != null) {
				new MessageDialog(GuiUtils.getOwnerFrame(this),
						"Invalid selector string", "Selector string '"
								+ selectorString + "' is not valid:<br>"
								+ validateMessage).setVisible(true);
				return false;
			}
		} else if (fslQueryRadio.isSelected()) {
			// TODO
		} else if (sparqlQueryRadio.isSelected()) {
			// TODO
		} else {
			LOG.warn("None of selector type radio buttons is selected!");
		}

		return true;
	}
}
