/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertiesPanel.java
 *
 * Created on 25.5.2010, 17:40:11
 */

package cz.muni.fi.fresneleditor.gui.mod.lens2.components;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import com.jidesoft.swing.CheckBoxListSelectionModel;

import cz.muni.fi.fresneleditor.gui.mod.lens2.PropertyVisibilityWrapper;

/**
 * 
 * @author namornik
 */
public class PropertiesPanel extends javax.swing.JPanel {

	/** Creates new form PropertiesPanel */
	public PropertiesPanel() {
		initComponents();

		ListSelectionListener listener = new ListSelectionListener() {

			@Override
			public void valueChanged(ListSelectionEvent e) {
				if (propertySelectorPanel1.propertySelector.getModel() == null
						|| propertySelectorPanel1.propertySelector.getModel()
								.getSize() <= 0)
					return;
				CheckBoxListSelectionModel lstSelModel = ((CheckBoxListSelectionModel) e
						.getSource());
				int changedValue = ((CheckBoxListSelectionModel) e.getSource())
						.getAnchorSelectionIndex();
				if (lstSelModel.isSelectedIndex(changedValue)) {
					// if(!orderPropertiesPanel1.propertyVisibilityJList1.getElements().contains((PropertyVisibilityWrapper)
					// propertySelectorPanel1.propertySelector.getModel().getElementAt(changedValue)));
					orderPropertiesPanel1.propertyVisibilityJList1
							.addElement((PropertyVisibilityWrapper) propertySelectorPanel1.propertySelector
									.getModel().getElementAt(changedValue));
				} else {
					if (((DefaultListModel) orderPropertiesPanel1.propertyVisibilityJList1
							.getModel())
							.contains((PropertyVisibilityWrapper) propertySelectorPanel1.propertySelector
									.getModel().getElementAt(changedValue)))
						orderPropertiesPanel1.propertyVisibilityJList1
								.removeElement((PropertyVisibilityWrapper) propertySelectorPanel1.propertySelector
										.getModel().getElementAt(changedValue));
				}

			}
		};
		propertySelectorPanel1.propertySelector.getCheckBoxListSelectionModel()
				.addListSelectionListener(listener);

		propertySelectorPanel1.allPropertiesBox
				.addActionListener(new ActionListener() {

					@Override
					public void actionPerformed(ActionEvent e) {
						orderPropertiesPanel1
								.useAllProperties(propertySelectorPanel1.allPropertiesBox
										.isSelected());
					}
				});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		propertySelectorPanel1 = new cz.muni.fi.fresneleditor.gui.mod.lens2.components.PropertySelectorPanel();
		orderPropertiesPanel1 = new cz.muni.fi.fresneleditor.gui.mod.lens2.components.OrderPropertiesPanel();

		setBackground(new java.awt.Color(213, 255, 213));

		propertySelectorPanel1.setName("propertySelectorPanel1"); // NOI18N
		propertySelectorPanel1
				.setPreferredSize(new java.awt.Dimension(200, 264));

		orderPropertiesPanel1.setName("orderPropertiesPanel1"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(propertySelectorPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										257, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(orderPropertiesPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										257, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(propertySelectorPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 322,
								Short.MAX_VALUE)
						.addComponent(orderPropertiesPanel1, 0, 0,
								Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public cz.muni.fi.fresneleditor.gui.mod.lens2.components.OrderPropertiesPanel orderPropertiesPanel1;
	public cz.muni.fi.fresneleditor.gui.mod.lens2.components.PropertySelectorPanel propertySelectorPanel1;

	// End of variables declaration//GEN-END:variables

	public void setModel(DefaultListModel properties) {
		propertySelectorPanel1.propertySelector.setModel(properties);
		// propertySelectorPanel1.allPropertiesBox.setSelected(properties.contains(PropertyVisibilityWrapper.ALL_PROPERTIES));
		orderPropertiesPanel1.propertyVisibilityJList1.removeAllElements();
	}

	public void setShowProperties(List<PropertyVisibilityWrapper> showProperties) {
		propertySelectorPanel1.setShowProperties(showProperties);
		orderPropertiesPanel1.setShowProperties(showProperties);
	}

	public List<PropertyVisibilityWrapper> getShowProperties() {
		return orderPropertiesPanel1.getShowProperties();
	}

	public List<PropertyVisibilityWrapper> getHideProperties() {
		return propertySelectorPanel1.getHideProperties();
	}

	public void setHideProperties(List<PropertyVisibilityWrapper> hideProperties) {
		propertySelectorPanel1.setHideProperties(hideProperties);
	}

}
