/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PurposePanel.java
 *
 * Created on 25.5.2010, 13:59:52
 */

package cz.muni.fi.fresneleditor.gui.mod.lens2.components;

import fr.inria.jfresnel.Lens;
import lenses.LensPurposeType;

/**
 * 
 * @author namornik
 */
public class PurposePanel extends javax.swing.JPanel {

	/** Creates new form PurposePanel */
	public PurposePanel() {
		initComponents();

		buttonGroup.setSelected(undefinedButton.getModel(), true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup = new javax.swing.ButtonGroup();
		undefinedButton = new javax.swing.JRadioButton();
		defaultButton = new javax.swing.JRadioButton();
		labelbutton = new javax.swing.JRadioButton();

		setBackground(new java.awt.Color(255, 241, 212));
		setBorder(javax.swing.BorderFactory.createTitledBorder("Lens purpose"));

		buttonGroup.add(undefinedButton);
		undefinedButton.setText("undefined");
		undefinedButton.setFocusable(false);
		undefinedButton.setName("undefinedButton"); // NOI18N
		undefinedButton.setOpaque(false);

		buttonGroup.add(defaultButton);
		defaultButton.setText("Default");
		defaultButton.setFocusable(false);
		defaultButton.setName("defaultButton"); // NOI18N
		defaultButton.setOpaque(false);

		buttonGroup.add(labelbutton);
		labelbutton.setText("Label");
		labelbutton.setFocusable(false);
		labelbutton.setName("labelbutton"); // NOI18N
		labelbutton.setOpaque(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(undefinedButton)
												.addComponent(defaultButton)
												.addComponent(labelbutton))
								.addContainerGap(163, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(undefinedButton)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(defaultButton)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(labelbutton)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup;
	private javax.swing.JRadioButton defaultButton;
	private javax.swing.JRadioButton labelbutton;
	private javax.swing.JRadioButton undefinedButton;

	// End of variables declaration//GEN-END:variables

	public void setPurpose(LensPurposeType purpose) {
		switch (purpose) {

		case DEFAULT:
			buttonGroup.setSelected(defaultButton.getModel(), true);
			break;
		case LABEL:
			buttonGroup.setSelected(labelbutton.getModel(), true);
			break;
		case NOT_SPECIFIED:
		default:
			buttonGroup.setSelected(undefinedButton.getModel(), true);
		}
	}

	public LensPurposeType getPurpose() {
		if (buttonGroup.isSelected(labelbutton.getModel()))
			return LensPurposeType.LABEL;
		else if (buttonGroup.isSelected(defaultButton.getModel()))
			return LensPurposeType.DEFAULT;
		return LensPurposeType.NOT_SPECIFIED;
	}

}
